login:
    path:     /login
    defaults: {_controller: AppBundle:Auth/Login:index }

login_check:
    path: /login_check

logout:
    path:     /logout

register:
    path:     /register
    defaults: {_controller: AppBundle:Auth/Register:index }


main:
    path:      /
    defaults:  { _controller: AppBundle:Main/Main:index }

chat:
    path:      /chat/{username}
    defaults:  { _controller: AppBundle:Main/Chat:index }

test:
    path:      /test
    defaults:  { _controller: AppBundle:Main/Test:index }

##

phoneConnectionOffer:
    path:      /phone/connection/offer/{userId}
    defaults:  { _controller: AppBundle:Phone/PhoneConnection:offer }

phoneConnectionAnswer:
    path:      /phone/connection/answer/{connectionId}
    defaults:  { _controller: AppBundle:Phone/PhoneConnection:answer }

phoneConnectionComplete:
    path:      /phone/connection/complete/{connectionId}
    defaults:  { _controller: AppBundle:Phone/PhoneConnection:complete }

phoneConnectionICECandidate:
    path:      /phone/connection/icecandidate/{userId}
    defaults:  { _controller: AppBundle:Phone/PhoneConnection:ICECandidate }