login:
    path:     /login
    defaults: {_controller: AppBundle:Auth/Login:index }

login_check:
    path: /login_check

logout:
    path:     /logout

register:
    path:     /register
    defaults: {_controller: AppBundle:Auth/Register:index }

##

main:
    path:      /
    defaults:  { _controller: AppBundle:Main/Main:index }

test:
    path:      /test
    defaults:  { _controller: AppBundle:Main/Test:index }

##

maintainOnline:
    path:      /maintainOnline
    defaults:  { _controller: AppBundle:Main/MaintainOnline:index }

##

chat:
    path:      /chat/{username}
    defaults:  { _controller: AppBundle:Main/Chat:index }

chat.text.send:
    path:      /chat/text/send/{userId}
    defaults:  { _controller: AppBundle:Main/ChatText:send }

##

chat.phone.connection.offer:
    path:      /chat/phone/connection/offer/{userId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:offer }

chat.phone.connection.answer:
    path:      /chat/phone/connection/answer/{connectionId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:answer }

chat.phone.connection.complete:
    path:      /chat/phone/connection/complete/{connectionId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:complete }

chat.phone.connection.ICECandidate:
    path:      /chat/phone/connection/icecandidate/{userId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:ICECandidate }