login:
    path:     /login
    defaults: {_controller: AppBundle:Auth/Login:index }

login_check:
    path: /login_check

logout:
    path:     /logout

register:
    path:     /register
    defaults: {_controller: AppBundle:Auth/Register:index }

##

main:
    path:      /
    defaults:  { _controller: AppBundle:Main/Main:index }

test:
    path:      /test
    defaults:  { _controller: AppBundle:Main/Test:index }

##

maintainOnline:
    path:      /maintainOnline
    defaults:  { _controller: AppBundle:Main/MaintainOnline:index }

contactList:
    path:      /contactList/{interlocutorId}
    defaults:  { _controller: AppBundle:Main/ContactList:index, interlocutorId: 0 }

##

chat:
    path:      /chat/{username}
    defaults:  { _controller: AppBundle:Main/Chat:index }

chat.text.send:
    path:      /chat/text/send/{userId}
    defaults:  { _controller: AppBundle:Main/ChatText:send }

##

chat.phone.connection.offer.audio:
    path:      /chat/phone/connection/offer/audio/{userId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:offer, video: false }

chat.phone.connection.offer.video:
    path:      /chat/phone/connection/offer/video/{userId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:offer, video: true }

chat.phone.connection.answer:
    path:      /chat/phone/connection/answer/{connectionId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:answer }

chat.phone.connection.reject:
    path:      /chat/phone/connection/reject/{connectionId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:reject }

chat.phone.connection.hangUp:
    path:      /chat/phone/connection/hangUp/{connectionId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:hangUp }

chat.phone.connection.complete:
    path:      /chat/phone/connection/complete/{connectionId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:complete }

chat.phone.connection.ICECandidate:
    path:      /chat/phone/connection/icecandidate/{userId}
    defaults:  { _controller: AppBundle:Main/ChatPhone:ICECandidate }