login:
    path:     /login
    defaults: {_controller: AppBundle:Auth/Login:index }

login_check:
    path: /login_check

logout:
    path:     /logout

register:
    path:     /register
    defaults: {_controller: AppBundle:Auth/Register:index }


main:
    path:      /
    defaults:  { _controller: AppBundle:Main/Main:index }