login:
    path:     /login/{language}
    defaults: {_controller: AppBundle:Main/Login:index, language: "" }

login_check:
    path: /login_check

logout:
    path:     /logout/{language}
    defaults: {_controller: AppBundle:Main/Login:logout }

register:
    path:     /register/{language}
    defaults: {_controller: AppBundle:Main/Register:index, language: "" }


example:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }