security:
    encoders:
        Entity\User:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity:
                class: Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern:  ^/
            anonymous: ~
            provider: main
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,      roles: ROLE_ADMIN }
        # to można usunąć gdy się chce by każdy mógł chodzić po stronie:
        - { path: ^/,           roles: ROLE_USER }