services:
    em:
        alias:      doctrine.orm.entity_manager

    ##

    user.repository:
        class:      Repository\UserRepository
        arguments:  [@em, @security.encoder_factory]

    user.register:
        class:      Service\User\UserRegister
        arguments:  [@user.repository, @user.logAs]

    user.logAs:
        class:      Service\User\UserLogAs
        arguments:  [@session, @security.context]

    ##

    call.repository:
        class:      Repository\CallRepository
        arguments:  [@em]

    message.repository:
        class:      Repository\MessageRepository
        arguments:  [@em]

    ##

    chat.text.send:
        arguments:  [@message.repository, @faye, @twig]
        class:      Service\Chat\Text\ChatTextSend

    ##

    chat.phone.connection:
        abstract:   true
        arguments:  [@faye, @call.repository]

    chat.phone.connection.offer:
        class:      Service\Chat\Phone\Connection\ConnectionOffer
        parent:     chat.phone.connection

    chat.phone.connection.answer:
        class:      Service\Chat\Phone\Connection\ConnectionAnswer
        parent:     chat.phone.connection

    chat.phone.connection.complete:
        class:      Service\Chat\Phone\Connection\ConnectionComplete
        parent:     chat.phone.connection

    chat.phone.connection.ICECandidate:
        class:      Service\Chat\Phone\Connection\ConnectionICECandidate
        parent:     chat.phone.connection

    ##

    faye:
        class:      Service\Faye\Faye
        arguments:  [@user.repository]

    ##

    date.twig.extension:
        class:        TwigExtensions\Date
        arguments:    [@translator]
        tags:
            -  { name: twig.extension }

    form.twig.extension:
        class:        TwigExtensions\Form
        tags:
            -  { name: twig.extension }

    avatar.twig.extension:
        class:        TwigExtensions\Avatar
        tags:
            -  { name: twig.extension }

    autop.twig.extension:
        class:        TwigExtensions\Autop
        tags:
            -  { name: twig.extension }
