services:
    em:
        alias:      doctrine.orm.entity_manager

    ##

    user.repository:
        class:      Repository\UserRepository
        arguments:  [@em, @security.encoder_factory]

    user.register:
        class:      Service\User\UserRegister
        arguments:  [@user.repository, @user.logAs]

    user.logAs:
        class:      Service\User\UserLogAs
        arguments:  [@session, @security.context]

    ##

    date.twig.extension:
        class:        TwigExtensions\Date
        arguments:    [@translator]
        tags:
            -  { name: twig.extension }

    form.twig.extension:
        class:        TwigExtensions\Form
        tags:
            -  { name: twig.extension }
